version: 2
jobs:
  vault-test:
    docker:
    - image: python:3.6.0
    steps:
    - checkout
    - run:
        name: Attempt to query vault
        command: |
          echo $VAULT_ROLE_ID
          pip install sshuttle
          echo "$VAULT_BASTION_SSH_KEY" > /tmp/ssh_key
          sudo sshuttle --verbose --daemon -e 'ssh -i /tmp/ssh_key' -r "ubuntu@3.83.48.211" 10.0.0.0/16:8200
          curl -v http://jhogan-star-grackle-vault-nlb-836cf59c11a64d57.elb.us-east-1.amazonaws.com:8200/v1/sys/leader
workflows:
  version: 2
  vault-testing:
    jobs:
    - vault-test:
        context: vault-test
