version 2.1

workflows:
  vault-testing:
    jobs:
      - run-tests:
        context: vault-test

jobs:
  run-tests:
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run:
          name: "echo environment variables from vault-test context"
          command: echo $VAULT_ROLE_ID
