version: 2
# this is now another commit eh?
sleepy_docker_build: &sleepy_docker_build
  docker:  [{image: 'alpine:latest'}]
  steps:
    - run:
        name: sleeeeeeeeep
        command: |
          time sleep $((RANDOM % 3600))

# lets do even more jobs
jobs:

  sleepy_docker_job0:
    <<: *sleepy_docker_build

  sleepy_docker_job1:
    <<: *sleepy_docker_build

  sleepy_docker_job2:
    <<: *sleepy_docker_build

  sleepy_docker_job3:
    <<: *sleepy_docker_build

  sleepy_docker_job4:
    <<: *sleepy_docker_build

  sleepy_docker_job5:
    <<: *sleepy_docker_build

  sleepy_docker_job6:
    <<: *sleepy_docker_build

  sleepy_docker_job7:
    <<: *sleepy_docker_build

  sleepy_docker_job8:
    <<: *sleepy_docker_build

  sleepy_docker_job9:
    <<: *sleepy_docker_build

  sleepy_docker_job10:
    <<: *sleepy_docker_build

  sleepy_docker_job11:
    <<: *sleepy_docker_build

  sleepy_docker_job12:
    <<: *sleepy_docker_build

  sleepy_docker_job13:
    <<: *sleepy_docker_build

  sleepy_docker_job14:
    <<: *sleepy_docker_build

  sleepy_docker_job15:
    <<: *sleepy_docker_build

  sleepy_docker_job16:
    <<: *sleepy_docker_build

  sleepy_docker_job17:
    <<: *sleepy_docker_build

  sleepy_docker_job18:
    <<: *sleepy_docker_build

  sleepy_docker_job19:
    <<: *sleepy_docker_build

  sleepy_docker_job20:
    <<: *sleepy_docker_build

  sleepy_docker_job21:
    <<: *sleepy_docker_build

  sleepy_docker_job22:
    <<: *sleepy_docker_build

  sleepy_docker_job23:
    <<: *sleepy_docker_build

  sleepy_docker_job24:
    <<: *sleepy_docker_build

  sleepy_docker_job25:
    <<: *sleepy_docker_build

  sleepy_docker_job26:
    <<: *sleepy_docker_build

  sleepy_docker_job27:
    <<: *sleepy_docker_build

  sleepy_docker_job28:
    <<: *sleepy_docker_build

  sleepy_docker_job29:
    <<: *sleepy_docker_build

  sleepy_docker_job30:
    <<: *sleepy_docker_build

  sleepy_docker_job31:
    <<: *sleepy_docker_build

  sleepy_docker_job32:
    <<: *sleepy_docker_build

  sleepy_docker_job33:
    <<: *sleepy_docker_build

  sleepy_docker_job34:
    <<: *sleepy_docker_build

  sleepy_docker_job35:
    <<: *sleepy_docker_build

  sleepy_docker_job36:
    <<: *sleepy_docker_build

  sleepy_docker_job37:
    <<: *sleepy_docker_build

  sleepy_docker_job38:
    <<: *sleepy_docker_build

  sleepy_docker_job39:
    <<: *sleepy_docker_build

  sleepy_docker_job40:
    <<: *sleepy_docker_build

  sleepy_docker_job41:
    <<: *sleepy_docker_build

  sleepy_docker_job42:
    <<: *sleepy_docker_build

  sleepy_docker_job43:
    <<: *sleepy_docker_build

  sleepy_docker_job44:
    <<: *sleepy_docker_build

  sleepy_docker_job45:
    <<: *sleepy_docker_build

  sleepy_docker_job46:
    <<: *sleepy_docker_build

  sleepy_docker_job47:
    <<: *sleepy_docker_build

  sleepy_docker_job48:
    <<: *sleepy_docker_build

  sleepy_docker_job49:
    <<: *sleepy_docker_build

  sleepy_docker_job50:
    <<: *sleepy_docker_build
  sleepy_docker_job51:
    <<: *sleepy_docker_build

  sleepy_docker_job52:
    <<: *sleepy_docker_build

  sleepy_docker_job53:
    <<: *sleepy_docker_build

  sleepy_docker_job54:
    <<: *sleepy_docker_build

  sleepy_docker_job55:
    <<: *sleepy_docker_build

  sleepy_docker_job56:
    <<: *sleepy_docker_build

  sleepy_docker_job57:
    <<: *sleepy_docker_build

  sleepy_docker_job58:
    <<: *sleepy_docker_build

  sleepy_docker_job59:
    <<: *sleepy_docker_build

  sleepy_docker_job60:
    <<: *sleepy_docker_build

  sleepy_docker_job61:
    <<: *sleepy_docker_build

  sleepy_docker_job62:
    <<: *sleepy_docker_build

  sleepy_docker_job63:
    <<: *sleepy_docker_build

  sleepy_docker_job64:
    <<: *sleepy_docker_build

  sleepy_docker_job65:
    <<: *sleepy_docker_build

  sleepy_docker_job66:
    <<: *sleepy_docker_build

  sleepy_docker_job67:
    <<: *sleepy_docker_build

  sleepy_docker_job68:
    <<: *sleepy_docker_build

  sleepy_docker_job69:
    <<: *sleepy_docker_build

  sleepy_docker_job70:
    <<: *sleepy_docker_build

  sleepy_docker_job71:
    <<: *sleepy_docker_build

  sleepy_docker_job72:
    <<: *sleepy_docker_build

  sleepy_docker_job73:
    <<: *sleepy_docker_build

  sleepy_docker_job74:
    <<: *sleepy_docker_build

  sleepy_docker_job75:
    <<: *sleepy_docker_build

  sleepy_docker_job76:
    <<: *sleepy_docker_build

  sleepy_docker_job77:
    <<: *sleepy_docker_build

  sleepy_docker_job78:
    <<: *sleepy_docker_build

  sleepy_docker_job79:
    <<: *sleepy_docker_build

  sleepy_docker_job80:
    <<: *sleepy_docker_build

  sleepy_docker_job81:
    <<: *sleepy_docker_build

  sleepy_docker_job82:
    <<: *sleepy_docker_build

  sleepy_docker_job83:
    <<: *sleepy_docker_build

  sleepy_docker_job84:
    <<: *sleepy_docker_build

  sleepy_docker_job85:
    <<: *sleepy_docker_build

  sleepy_docker_job86:
    <<: *sleepy_docker_build

  sleepy_docker_job87:
    <<: *sleepy_docker_build

  sleepy_docker_job88:
    <<: *sleepy_docker_build

  sleepy_docker_job89:
    <<: *sleepy_docker_build

  sleepy_docker_job90:
    <<: *sleepy_docker_build

  sleepy_docker_job91:
    <<: *sleepy_docker_build

  sleepy_docker_job92:
    <<: *sleepy_docker_build

  sleepy_docker_job93:
    <<: *sleepy_docker_build

  sleepy_docker_job94:
    <<: *sleepy_docker_build

  sleepy_docker_job95:
    <<: *sleepy_docker_build

  sleepy_docker_job96:
    <<: *sleepy_docker_build

  sleepy_docker_job97:
    <<: *sleepy_docker_build

  sleepy_docker_job98:
    <<: *sleepy_docker_build

  sleepy_docker_job99:
    <<: *sleepy_docker_build

  sleepy_docker_job100:
    <<: *sleepy_docker_build  

workflows:
  version: 2
  lots_o_jobs:
    jobs:
      - sleepy_docker_job0
      - sleepy_docker_job1
      - sleepy_docker_job2
      - sleepy_docker_job3
      - sleepy_docker_job4
      - sleepy_docker_job5
      - sleepy_docker_job6
      - sleepy_docker_job7
      - sleepy_docker_job8
      - sleepy_docker_job9
      - sleepy_docker_job10
      - sleepy_docker_job11
      - sleepy_docker_job12
      - sleepy_docker_job13
      - sleepy_docker_job14
      - sleepy_docker_job15
      - sleepy_docker_job16
      - sleepy_docker_job17
      - sleepy_docker_job18
      - sleepy_docker_job19
      - sleepy_docker_job20
      - sleepy_docker_job21
      - sleepy_docker_job22
      - sleepy_docker_job23
      - sleepy_docker_job24
      - sleepy_docker_job25
      - sleepy_docker_job26
      - sleepy_docker_job27
      - sleepy_docker_job28
      - sleepy_docker_job29
      - sleepy_docker_job30
      - sleepy_docker_job31
      - sleepy_docker_job32
      - sleepy_docker_job33
      - sleepy_docker_job34
      - sleepy_docker_job35
      - sleepy_docker_job36
      - sleepy_docker_job37
      - sleepy_docker_job38
      - sleepy_docker_job39
      - sleepy_docker_job40
      - sleepy_docker_job41
      - sleepy_docker_job42
      - sleepy_docker_job43
      - sleepy_docker_job44
      - sleepy_docker_job45
      - sleepy_docker_job46
      - sleepy_docker_job47
      - sleepy_docker_job48
      - sleepy_docker_job49
      - sleepy_docker_job50
      - sleepy_docker_job51
      - sleepy_docker_job52
      - sleepy_docker_job53
      - sleepy_docker_job54
      - sleepy_docker_job55
      - sleepy_docker_job56
      - sleepy_docker_job57
      - sleepy_docker_job58
      - sleepy_docker_job59
      - sleepy_docker_job60
      - sleepy_docker_job61
      - sleepy_docker_job62
      - sleepy_docker_job63
      - sleepy_docker_job64
      - sleepy_docker_job65
      - sleepy_docker_job66
      - sleepy_docker_job67
      - sleepy_docker_job68
      - sleepy_docker_job69
      - sleepy_docker_job70
      - sleepy_docker_job71
      - sleepy_docker_job72
      - sleepy_docker_job73
      - sleepy_docker_job74
      - sleepy_docker_job75
      - sleepy_docker_job76
      - sleepy_docker_job77
      - sleepy_docker_job78
      - sleepy_docker_job79
      - sleepy_docker_job80
      - sleepy_docker_job81
      - sleepy_docker_job82
      - sleepy_docker_job83
      - sleepy_docker_job84
      - sleepy_docker_job85
      - sleepy_docker_job86
      - sleepy_docker_job87
      - sleepy_docker_job88
      - sleepy_docker_job89
      - sleepy_docker_job90
      - sleepy_docker_job91
      - sleepy_docker_job92
      - sleepy_docker_job93
      - sleepy_docker_job94
      - sleepy_docker_job95
      - sleepy_docker_job96
      - sleepy_docker_job97
      - sleepy_docker_job98
      - sleepy_docker_job99
      - sleepy_docker_job100
