version: 2
# this is now another commit eh? sure is
sleepy_docker_build: &sleepy_docker_build
  docker:  [{image: 'alpine:latest'}]
  steps:
    - run:
        name: sleeeeeeeeep
        command: |
          for i in 1 2 3 4 5 6 7 8 9 10 11 12; do 
            SLEEP_TIME=$((RANDOM % 300));
            echo "I am $i and I so sweepy, might just sleep for $SLEEP_TIME...";
            time sleep $SLEEP_TIME;
            echo "Ok, ok, $i is up";
          done

# lets do even more jobs
jobs:

  sleepy_docker_job0:
    <<: *sleepy_docker_build

  sleepy_docker_job1:
    <<: *sleepy_docker_build

  sleepy_docker_job2:
    <<: *sleepy_docker_build

  sleepy_docker_job3:
    <<: *sleepy_docker_build

  sleepy_docker_job4:
    <<: *sleepy_docker_build

  sleepy_docker_job5:
    <<: *sleepy_docker_build

  sleepy_docker_job6:
    <<: *sleepy_docker_build

  sleepy_docker_job7:
    <<: *sleepy_docker_build

  sleepy_docker_job8:
    <<: *sleepy_docker_build

  sleepy_docker_job9:
    <<: *sleepy_docker_build

  sleepy_docker_job10:
    <<: *sleepy_docker_build

  sleepy_docker_job11:
    <<: *sleepy_docker_build

  sleepy_docker_job12:
    <<: *sleepy_docker_build

workflows:
  version: 2
  lots_o_jobs:
    jobs:
      - sleepy_docker_job0
      - sleepy_docker_job1
      - sleepy_docker_job2
      - sleepy_docker_job3
      - sleepy_docker_job4
      - sleepy_docker_job5
      - sleepy_docker_job6
      - sleepy_docker_job7
      - sleepy_docker_job8
      - sleepy_docker_job9
      - sleepy_docker_job10
      - sleepy_docker_job11
      - sleepy_docker_job12
