version: 2
jobs:
  vault-test:
    docker:
    - image: python:3.6.0
    steps:
    - checkout
    - run:
        name: Attempt to query vault
        command: |
          echo $VAULT_ROLE_ID
          ssh-add <(echo "$VAULT_BASTION_SSH_KEY" | base64 -d)
          curl icanhazip.com
          # ssh -o StrictHostKeyChecking=no -N -f -L 8200::8200 ubuntu@3.83.48.211
          pip install sshuttle
          sshuttle \
            --ssh-cmd='ssh -o StrictHostKeyChecking=no' \
            --verbose \
            --remote \
            --method=nat \
            "ubuntu@3.83.48.211" 10.0.0.0/16:8200
          curl -v --max-time 5 http://jhogan-star-grackle-vault-nlb-836cf59c11a64d57.elb.us-east-1.amazonaws.com:8200/v1/sys/leader
workflows:
  version: 2
  vault-testing:
    jobs:
    - vault-test:
        context: vault-test
