version: 2
jobs:
  vault-test:
    docker:
    - image: python:3.6.0
    steps:
    - checkout
    - run:
        name: Attempt to query vault
        command: |
          echo $VAULT_ROLE_ID
          ssh-add <(echo "$VAULT_BASTION_SSH_KEY" | base64 -d)
          curl icanhazip.com
          tunnels=''
          for IP in "$(dig +short "$VAULT_HOST")"; do
            tunnels="$tunnels -L 8200:$IP:8200"
          done
          ssh -o StrictHostKeyChecking=no -N -f "$tunnels" ubuntu@3.83.48.211
          #pip install sshuttle
          #apt update && apt install --yes iptables
          #sshuttle --listen=0.0.0.0            --verbose             --ssh-cmd='ssh -o StrictHostKeyChecking=no'             --remote="ubuntu@3.83.48.211"             10.0.0.0/16:8200
          curl -v --max-time 5 "http://$VAULT_HOST:8200/v1/sys/leader"
workflows:
  version: 2
  vault-testing:
    jobs:
    - vault-test:
        context: vault-test
